use_frameworks!

platform :ios, '8.0'

target 'RGNavigationController_Example' do
  pod 'RGNavigationController', :path => '../'

  target 'RGNavigationController_Tests' do
    inherit! :search_paths

    
  end
end
